---
driver:
  name: ec2
  region: us-east-1
  availability_zone: c
  subnet_id: <%= ENV['AWS_SUBNET_ID']  %>
  security_group_ids:
    - <%= ENV['AWS_SG']  %>
  associate_public_ip: true
  interface: dns
  instance_type: t3a.micro
  retryable_tries: 180
  tags:
    Name: "amimoto-die-hard"

transport:
  username: ec2-user
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID']  %>
  ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>

provisioner:
  name: shell

platforms:
  - name: hvm-amimoto
    driver:
      image_id: ami-080b18709557d5afd # 6.0
  - name: woo-modphp-amimoto
    driver:
      image_id: ami-74d0570b # 5.1.0
    verifier:
      name: shell
      command: bundle exec rspec -fd spec/legacy/
  - name: modphp-amimoto
    driver:
      image_id: ami-07889a02ff253da5c # 6.0
  - name: woo-hvm-amimoto
    driver:
      image_id: ami-c6d750b9 # 5.1.0
    verifier:
      name: shell
      command: bundle exec rspec -fd spec/legacy/
  - name:  autoscale-amimoto
    driver:
      image_id: ami-dfd354a0 # 5.1.0
    verifier:
      name: shell
      command: bundle exec rspec -fd spec/legacy/

verifier:
  name: shell
  command: bundle exec rspec -fd spec/2019/
#  sleep: 300

suites:
  - name: default
    run_list:
    attributes:
<%
## Periodic outputs for CircleCI
if ENV['CI']
  ppid = Process.pid
  Process.fork {
    loop {
      puts "."
      begin
        Process.getpgid( ppid )
        sleep 20
      rescue
        exit 0
      end
    }
  }
end
%>
