---
driver:
  name: ec2
  region: us-east-1
  availability_zone: us-east-1c
  subnet_id: <%= ENV['AWS_SUBNET_ID']  %>
  associate_public_ip: true
  instance_type: t2.micro

transport:
  username: ec2-user
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID']  %>
  ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>

provisioner:
  name: shell

platforms:
  - name: hiphop-amimoto
    driver:
      image_id: ami-cb4865a1 # 1.1.2
  - name: modphp-amimoto
    driver:
      image_id: ami-9e9ebef4 # 1.0.1
  - name: http2-amimoto
    driver:
      image_id: ami-c39ebea9 # 1.0.1
  - name: pvm-amimoto
    driver:
      image_id: ami-0d6e4367 # 1.4.2
      instance_type: m1.small
  - name: hvm-amimoto
    driver:
      image_id: ami-886241e2 # 1.2.1
  - name: woo-amimoto
    driver:
      image_id: ami-3165485b # 1.0.2

verifier:
  name: shell
  command: bundle exec rspec -fd
#  sleep: 300

suites:
  - name: default
    run_list:
    attributes:
<%
## Periodic outputs for CircleCI
if ENV['CI']
  ppid = Process.pid
  Process.fork {
    loop {
      puts "."
      begin
        Process.getpgid( ppid )
        sleep 20
      rescue
        exit 0
      end
    }
  }
end
%>
